#if !defined(_WIN32) && !defined(_DEFAULT_SOURCE)
#define _DEFAULT_SOURCE
#endif
#define _CRT_SECURE_NO_WARNINGS
#define SDL_MAIN_HANDLED

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#if defined(_WIN32)
#include <io.h>
#ifdef CTR_EDITOR
#include <process.h>
#endif
#else
#ifdef CTR_EDITOR
#include <sys/types.h>
#include <sys/wait.h>
#endif
#include <unistd.h>
#endif

#if __GNUC__
#include <SDL3/SDL.h>
#include <SDL3/SDL_main.h>
#define _EnterCriticalSection(x)
#define EnterCriticalSection(x)
#define ExitCriticalSection()
#endif

#ifdef CTR_AP
#include "ap/ap_version.h"
#include "ap/ap_tracker.h"
#include "ap/ap_vendor_versions.h" // generated by cmake/APVendorCheck.cmake
#endif
#include "platform/native_assets.h"
#include "platform/native_clip_scratch.h"
#include "platform/native_log.h"
#include "platform/native_memory.h"
#include "platform/native_perf.h"
#include "platform/native_ptr_scratch.h"
#include "platform/native_replay_scheduler.h"
#include "platform/native_savestate.h"

#ifndef __GNUC__
#define __attribute__(x)
#endif

#include <platform.h>

#include "game/game_unity.h"

#include "game/zGlobal_RDATA.c"
#include "game/zGlobal_DATA.c"
#include "game/zGlobal_SDATA.c"
#include "game/widescreen.c"

#undef RECT

#include "platform/native_disc_image.c"
#include "platform/native_assets.c"
#include "platform/native_audio.c"
#include "platform/native_clip_scratch.c"
#include "platform/native_memory.c"
#include "platform/native_checkpoint.c"
#include "platform/native_checkpoint_file.c"
#include "platform/native_cd.c"
#include "platform/native_gpu_links.c"
#include "platform/native_gpu.c"
#include "platform/native_gte_core.c"
#include "platform/native_glad.c"
#include "platform/native_input.c"
#include "platform/native_inline_c.c"
#include "platform/native_libapi.c"
#include "platform/native_libetc.c"
#include "platform/native_libgte.c"
#include "platform/native_libgpu.c"
#include "platform/native_libpad.c"
#include "platform/native_libspu.c"
#include "platform/native_log.c"
#include "platform/native_memcard.c"
#include "platform/native_memcard_adapter.c"
#include "platform/native_perf.c"
#include "platform/native_ptr_scratch.c"
#include "platform/native_platform.c"
#include "platform/native_replay_scheduler.c"
#include "platform/native_renderer.c"
#include "platform/native_savestate.c"
#include "platform/native_state.c"
#include "platform/native_str.c"
#include "platform/native_config.c"
#include "platform/native_custom_track_manager.c"
#include "platform/native_custom_tracks.c"

#ifndef CC
#if __GNUC__
#if _WIN32
#ifndef __clang__
#define CC "MINGW-GCC"
#else
#define CC "MINGW-CLANG"
#endif
#else
#ifndef __clang__
#define CC "GCC"
#else
#define CC "CLANG"
#endif
#endif
#elif defined(_MSC_VER)
#define CC "MSVC"
#else
#define CC "Unknown"
#endif
#endif

#ifndef CTR_NATIVE_VERSION
#define CTR_NATIVE_VERSION "0.0.0-dev"
#endif

#ifndef CTR_NATIVE_BUILD_ID
#define CTR_NATIVE_BUILD_ID "unknown"
#endif

static int NativeConsole_ShouldPauseOnError(void)
{
#if defined(_WIN32)
	DWORD consoleProcesses[2];
	DWORD consoleProcessCount;

	if (GetConsoleWindow() == NULL)
		return 0;

	consoleProcessCount = GetConsoleProcessList(consoleProcesses, (DWORD)(sizeof(consoleProcesses) / sizeof(consoleProcesses[0])));
	return (consoleProcessCount == 1) && (consoleProcesses[0] == GetCurrentProcessId());
#else
	return 0;
#endif
}

static s32 NativeConsole_Return(const u32 result)
{
	if ((result != 0) && NativeConsole_ShouldPauseOnError())
	{
		fflush(stdout);
		fflush(stderr);
		fprintf(stderr, "\n[CTR Native] Press Enter to close this window...");
		fflush(stderr);

		while (getchar() != '\n' && !feof(stdin))
		{
		}
	}

	return (s32)result;
}

// TODO(aalhendi): just make an argparser?
static int NativeArg_IsVersion(const char *arg)
{
	return (arg != NULL) && ((strcmp(arg, "--version") == 0) || (strcmp(arg, "-v") == 0));
}

#ifdef CTR_EDITOR
static int NativeArg_HasSuffix(const char *arg, const char *suffix)
{
	size_t argLength;
	size_t suffixLength;

	if ((arg == NULL) || (suffix == NULL))
		return 0;

	argLength = strlen(arg);
	suffixLength = strlen(suffix);
	return (argLength >= suffixLength) && (strcmp(arg + argLength - suffixLength, suffix) == 0);
}
#endif

#ifdef CTR_EDITOR
#if defined(_WIN32)
static int EditorArgs_FindPython(char *destination, size_t destinationSize)
{
	char localAppData[MAX_PATH];
	DWORD length;
	const char *suffixes[] = {
	    "\\Python\\bin\\python.exe",
	    "\\Python\\pythoncore-3.14-64\\python.exe",
	    "\\Programs\\Python\\Python310\\python.exe",
	};

	length = GetEnvironmentVariableA("CTR_EDITOR_PYTHON", destination, (DWORD)destinationSize);
	if ((length > 0) && (length < destinationSize) && (GetFileAttributesA(destination) != INVALID_FILE_ATTRIBUTES))
		return 1;

	length = SearchPathA(NULL, "python.exe", NULL, (DWORD)destinationSize, destination, NULL);
	if ((length > 0) && (length < destinationSize))
		return 1;

	length = GetEnvironmentVariableA("LOCALAPPDATA", localAppData, (DWORD)sizeof(localAppData));
	if ((length == 0) || (length >= sizeof(localAppData)))
		return 0;

	for (size_t index = 0; index < sizeof(suffixes) / sizeof(suffixes[0]); index++)
	{
		if (snprintf(destination, destinationSize, "%s%s", localAppData, suffixes[index]) < 0)
			continue;
		if (GetFileAttributesA(destination) != INVALID_FILE_ATTRIBUTES)
			return 1;
	}

	return 0;
}
#endif

static int EditorArgs_RunProjectSupervisor(int argc, char *argv[])
{
	char **supervisorArgv;
	int result;
	char executable[4096];
	char script[4096];
	char *defaultArgv[5];
#if defined(_WIN32)
	char pythonPath[MAX_PATH];
#endif

	if (argc == 1)
	{
#if defined(_WIN32)
		DWORD length = GetModuleFileNameA(NULL, executable, sizeof(executable));
		if (length == 0 || length >= sizeof(executable)) return 70;
#else
		ssize_t length = readlink("/proc/self/exe", executable, sizeof(executable) - 1);
		if (length <= 0) return 70;
		executable[length] = 0;
#endif
		strcpy(script, executable);
		char *slash = strrchr(script, '/');
		char *backslash = strrchr(script, '\\');
		if (backslash && (!slash || backslash > slash)) slash = backslash;
		if (!slash || (size_t)(slash - script) + 30 >= sizeof(script)) return 70;
		strcpy(slash + 1, "tools/run_editor_project.py");
		defaultArgv[0] = executable;
		defaultArgv[1] = script;
		defaultArgv[2] = "--binary";
		defaultArgv[3] = executable;
		defaultArgv[4] = NULL;
		argv = defaultArgv;
		argc = 4;
	}
	if (!NativeArg_HasSuffix(argv[1], "run_editor_project.py"))
		return -1;

	supervisorArgv = calloc((size_t)argc + 1, sizeof(*supervisorArgv));
	if (supervisorArgv == NULL)
	{
		fprintf(stderr, "[CTR Editor] Could not allocate project-supervisor arguments.\n");
		return 70;
	}

	supervisorArgv[0] = "python";
	for (int argIndex = 1; argIndex < argc; argIndex++)
		supervisorArgv[argIndex] = argv[argIndex];

	fprintf(stdout, "[CTR Editor] Starting validated project supervisor: %s\n", argv[1]);
	fflush(stdout);

#if defined(_WIN32)
	if (!EditorArgs_FindPython(pythonPath, sizeof(pythonPath)))
		result = -1;
	else
	{
		supervisorArgv[0] = pythonPath;
		result = (int)_spawnv(_P_WAIT, pythonPath, (const char *const *)supervisorArgv);
	}
#else
	{
		pid_t child = fork();
		if (child == 0)
		{
			execvp("python3", supervisorArgv);
			_exit(127);
		}
		if (child < 0)
			result = -1;
		else if (waitpid(child, &result, 0) < 0)
			result = -1;
		else if (WIFEXITED(result))
			result = WEXITSTATUS(result);
		else
			result = 128;
	}
#endif

	free(supervisorArgv);
	if (result == -1)
	{
		fprintf(stderr,
		        "[CTR Editor] Could not start Python. Set CTR_EDITOR_PYTHON to python.exe, then retry.\n");
		return 69;
	}

	return result;
}
#endif


int main(int argc, char *argv[])
{
#ifdef CTR_EDITOR
	{
		int supervisorResult = EditorArgs_RunProjectSupervisor(argc, argv);
		if (supervisorResult >= 0)
			return NativeConsole_Return((u32)supervisorResult);
	}
#endif

	for (int argIndex = 1; argIndex < argc; argIndex++)
	{
#ifdef CTR_EDITOR
		if (strcmp(argv[argIndex], "--editor-self-test") == 0)
			return Editor_RunSelfTests();
#endif
		if (NativeArg_IsVersion(argv[argIndex]))
		{
#ifdef CTR_EDITOR
			printf("CTR Native Editor %s (%s)\n", CTR_NATIVE_VERSION, CTR_NATIVE_BUILD_ID);
#else
			printf("CTR Native %s (%s)\n", CTR_NATIVE_VERSION, CTR_NATIVE_BUILD_ID);
#endif
			return 0;
		}
	}

#ifdef CTR_EDITOR
	Editor_ConfigureFromArgs(argc, argv);
#endif

#ifdef CTR_EDITOR
	printf("[CTR Editor] Starting...\n");
#else
	printf("[CTR Native] Starting...\n");
#endif
	fflush(stdout);

	const char *sdlBasePath = SDL_GetBasePath();
	printf("[CTR Native] SDL base path: %s\n", sdlBasePath ? sdlBasePath : "(null)");
	fflush(stdout);

	if (!NativeAssets_Init(sdlBasePath))
	{
		fprintf(stderr, "[CTR Native] Failed to initialize asset paths.\n");
		return NativeConsole_Return(1);
	}

#ifdef CTR_EDITOR
	printf("[CTR Editor] Version: %s (%s)\n", CTR_NATIVE_VERSION, CTR_NATIVE_BUILD_ID);
#else
	printf("[CTR Native] Version: %s (%s)\n", CTR_NATIVE_VERSION, CTR_NATIVE_BUILD_ID);
#endif
#ifdef CTR_AP
	// The CTR-AP RELEASE identifier (client + companion apworld pair), distinct
	// from the engine version above -- this is the line a bug report should quote.
	printf("[CTR-AP] Release: %s\n", CTR_AP_VERSION);
	// Pinned networking stack (ap/vendor/versions.lock); names the exact deps a
	// bug report was built against (issue #78).
	printf("[CTR-AP] Vendor: %s\n", CTR_AP_VENDOR_VERSIONS);
#endif
	printf("[CTR Native] Built with: " CC "\n");
	printf("[CTR Native] Base: %s\n", NativeAssets_GetBaseDir());
	printf("[CTR Native] Assets: %s\n", NativeAssets_GetAssetDir());
	fflush(stdout);

	if (chdir(NativeAssets_GetBaseDir()) != 0)
	{
		fprintf(stderr, "[CTR Native] Failed to enter base directory: %s\n", NativeAssets_GetBaseDir());
		return NativeConsole_Return(1);
	}

#ifdef CTR_AP
	// Arm the crash reporter as early as its only dependency allows (the crash
	// file is opened by relative path, so the base-dir chdir must have landed).
	// Anything from here on -- asset validation, SDL/renderer init -- now leaves
	// a ctr-ap-crash.txt block instead of dying silently (Intel HD 4000 class).
	AP_CrashInstall();
#endif

	if (!NativeAssets_Validate())
	{
#if !defined(_WIN32)
		// On-screen guidance for players who launched with no terminal in sight
		// (e.g. a Steam Deck in Gaming Mode) and never see the stderr report.
		// Windows is excluded: a double-clicked console build already opens a
		// console that the pause below keeps readable, and a modal box would
		// hang unattended runs. SDL message boxes work before SDL_Init and fail
		// gracefully on headless hosts.
		if (!isatty(STDERR_FILENO))
		{
			char assetsMessage[1280];
			snprintf(assetsMessage, sizeof(assetsMessage),
			         "Game assets are missing or incomplete.\n\n"
			         "Place a raw .bin disc image of your own NTSC-U Crash Team Racing disc in the assets folder next to the game:\n\n"
			         "%s\n\n"
			         "Any filename ending in .bin works. See the setup guide for details.",
			         NativeAssets_GetAssetDir());
			SDL_ShowSimpleMessageBox(SDL_MESSAGEBOX_ERROR, "CTR Native", assetsMessage, NULL);
		}
#endif

		return NativeConsole_Return(1);
	}

	// Load user options (config.ini in the working dir) before the game boots so
	// startup-time toggles (e.g. skip_intro) are honoured on the first frame.
	NativeConfig_Load();

#ifdef CTR_EDITOR
	// Headless dump runs apply --editor-dump-mute / --editor-dump-skip-intro
	// after the config load, so config.ini cannot override them.
	Editor_ApplyDumpRuntimeOverrides();
#endif

#ifdef CTR_CUSTOM_TRACKS
	// Parse [CustomTracks] and hash-verify the configured track once, before the
	// game boots, so the first level load already knows whether the loader is
	// armed. Verification here rather than at first read keeps the multi-MiB
	// digest out of the load path and makes a content refusal visible at startup
	// instead of on the warp pad.
	CustomTrack_Load();
#endif

#if defined(CTR_INTERNAL)
	if (NativeReplayScheduler_PrepareReportFromArgs(argc, argv) != 0)
	{
		return NativeConsole_Return(1);
	}
#endif

#if defined(CTR_EDITOR)
#define CTR_WINDOW_TITLE "CTR Native Editor"
#elif defined(CTR_AP)
	// Window title carries the CTR-AP release so a screenshot alone names the
	// build (release-management plan, proposal 1).
#define CTR_WINDOW_TITLE "Crash Team Racing - CTR-AP " CTR_AP_VERSION
#else
#define CTR_WINDOW_TITLE "Crash Team Racing"
#endif

#ifdef USE_16BY9
	printf("[CTR Native] Widescreen\n");
	Platform_Init(CTR_WINDOW_TITLE, 1280, 720);
#else
	printf("[CTR Native] 4:3\n");
	Platform_Init(CTR_WINDOW_TITLE, 800, 600);
#endif

#if defined(CTR_INTERNAL)
	if (NativePerf_ConfigureFromArgs(argc, argv) != 0)
	{
		Platform_LogFlush();
		Platform_Shutdown();
		return NativeConsole_Return(1);
	}
#endif

	Platform_InitScratchpad();
	Platform_RepairResidentPointers(0);

#if defined(CTR_INTERNAL)
	if (NativeReplayScheduler_ConfigureFromArgs(argc, argv) != 0)
	{
		Platform_LogFlush();
		Platform_Shutdown();
		return NativeConsole_Return(1);
	}
#else
	(void)argc;
	(void)argv;
#endif

	const int result = CTR_Main();

	Platform_Shutdown();
	return NativeConsole_Return(result);
}
