#!/usr/bin/env python3
"""Generate ap/ap_box_model_framed_data.h: the AP box built the way the retail
"?" item crate is built.

The retail crate_question near-LOD model (measured in the editor with
--editor-dump-model 8, identical on every retail track checked) is a flat cube
whose six sides are each split into ten triangles: a centre square covering
the middle two thirds (42..212 of 0..255), textured with the 64x64 face, and a
flat border ring of four trapezoids (two triangles each), every trapezoid
textured with the whole 16x16 wood rect, stretched: across the strip (outer
edge to inner edge) is the rect's u axis, along the edge is its v axis. Sides
are shaded by vertex colour, 0x40 to 0xC0 grey, one shade per side.

This generator rebuilds that structure from scratch on the AP cube (extent
32..224, border 32 units, so the same one-sixth proportion); no retail bytes
are copied. Face orientation per side is the verified outside-view table of
ap/ap_box_model_data.h (texture top toward +vertical on the four walls). The
per-triangle layouts address the AP atlas directly (tools/apbox-texture
README rect map) and stop one texel short of each rect's far edge, as
ap/ap_box_texture.c does for the face.

    python gen_framed_model.py ../../ap/ap_box_model_framed_data.h
"""
import sys

LO, HI, INSET = 32, 224, 32
FACE = (16, 0, 64, 64)   # atlas rect x, y, w, h (AP_BOX_TEXTURE_FACE_*)
WOOD = (0, 0, 16, 16)    # AP_BOX_TEXTURE_WOOD_*
TPAGE = 0x0069 | 0x8000  # retail crate_question face tpage | AP_TPAGE_SIDELOAD_BIT
CLUT = 0x3F6A

# side: plane axis, plane value, u = (axis, sign), v = (axis, sign), colour index.
# Axes are vertex bytes: b0 horizontal, b1 depth, b2 vertical (up = +b2).
# u/v signs are the outside-view table derived from ap_box_model_data.h.
SIDES = [
    ("front",  1, LO, (0, -1), (2, -1), 0),
    ("back",   1, HI, (0, +1), (2, -1), 1),
    ("left",   0, LO, (1, +1), (2, -1), 2),
    ("right",  0, HI, (1, -1), (2, -1), 3),
    ("top",    2, HI, (0, -1), (1, -1), 4),
    ("bottom", 2, LO, (0, +1), (1, -1), 5),
]
# Retail crate shades for the same planes (b1 low 0x40, b1 high 0xC0, b0 low
# 0xA0, b0 high 0x60, top and bottom 0x80).
COLOURS = [0x00404040, 0x00C0C0C0, 0x00A0A0A0, 0x00606060, 0x00808080, 0x00808080]


def point(side, s, t):
    """Vertex on a side at normalized outside-view (s right, t down)."""
    _, ax, val, (ua, us), (va, vs), _ = side
    p = [0, 0, 0]
    p[ax] = val
    p[ua] = LO + round((s if us > 0 else 1 - s) * (HI - LO))
    p[va] = LO + round((t if vs > 0 else 1 - t) * (HI - LO))
    return tuple(p)


def cross(a, b):
    return (a[1] * b[2] - a[2] * b[1], a[2] * b[0] - a[0] * b[2], a[0] * b[1] - a[1] * b[0])


def outward(tri):
    a, b, c = tri
    n = cross([b[i] - a[i] for i in range(3)], [c[i] - a[i] for i in range(3)])
    centre = [(a[i] + b[i] + c[i]) / 3 - 128 for i in range(3)]
    return sum(n[i] * centre[i] for i in range(3)) > 0


def build():
    k = INSET / (HI - LO)
    tris = []  # (verts, uvs, colour)
    fx, fy, fw, fh = FACE
    wx, wy, ww, wh = WOOD

    def face_uv(s, t):
        return (fx + round((s - k) / (1 - 2 * k) * (fw - 2)), fy + round((t - k) / (1 - 2 * k) * (fh - 2)))

    for side in SIDES:
        ci = side[5]
        # centre square, outside-view corners
        tl, tr, br, bl = (k, k), (1 - k, k), (1 - k, 1 - k), (k, 1 - k)
        for a, b, c in ((br, bl, tl), (br, tl, tr)):
            tris.append(([point(side, *q) for q in (a, b, c)], [face_uv(*q) for q in (a, b, c)], ci))
        # border ring: (outer 1, outer 2, inner 2, inner 1) clockwise from the top
        strips = [
            ((0, 0), (1, 0), (1 - k, k), (k, k)),          # top
            ((1, 0), (1, 1), (1 - k, 1 - k), (1 - k, k)),  # right
            ((1, 1), (0, 1), (k, 1 - k), (1 - k, 1 - k)),  # bottom
            ((0, 1), (0, 0), (k, k), (k, 1 - k)),          # left
        ]
        for o1, o2, i2, i1 in strips:
            uv = {o1: (wx, wy), o2: (wx, wy + wh - 2), i2: (wx + ww - 2, wy + wh - 2), i1: (wx + ww - 2, wy)}
            for a, b, c in ((o1, o2, i2), (o1, i2, i1)):
                tris.append(([point(side, *q) for q in (a, b, c)], [uv[q] for q in (a, b, c)], ci))
    # every triangle faces outward with the same winding as the plain cube
    fixed = []
    for verts, uvs, ci in tris:
        if not outward(verts):
            verts = [verts[0], verts[2], verts[1]]
            uvs = [uvs[0], uvs[2], uvs[1]]
        fixed.append((verts, uvs, ci))
    return fixed


def main(out):
    tris = build()
    assert len(tris) == 60
    lines = []
    w = lines.append
    w("// GENERATED by tools/apbox-texture/gen_framed_model.py -- do not edit by hand.")
    w("//")
    w("// The AP box built like the retail \"?\" item crate: every side is a centre")
    w("// square carrying the 64x64 face and a flat border ring of four strips carrying")
    w("// the 16x16 wood rect, shaded per side like the retail crate. Same 32..224")
    w("// extent as the plain cube in ap_box_model_data.h, so size and spawn lift do not")
    w("// change. De-indexed: every triangle restarts the strip and has its own layout.")
    w("")
    w("#define AP_BOX_FRAMED_NUM_VERTS %d" % (len(tris) * 3))
    w("#define AP_BOX_FRAMED_NUM_TRIS %d" % len(tris))
    w("#define AP_BOX_FRAMED_NUM_COLORS %d" % len(COLOURS))
    w("")
    w("static const u32 s_apBoxFramedColors[AP_BOX_FRAMED_NUM_COLORS] = {")
    w("\t" + ", ".join("0x%08x" % c for c in COLOURS) + ",")
    w("};")
    w("")
    w("// byte0 = horizontal, byte1 = depth, byte2 = vertical; the vertical byte is")
    w("// pre-decremented where byte0 >= 128 (packed XY carry, see ap_box_model_data.h).")
    w("static const u8 s_apBoxFramedVerts[AP_BOX_FRAMED_NUM_VERTS * 3] = {")
    for verts, _, _ in tris:
        row = []
        for x, y, z in verts:
            row.append("%3d,%3d,%3d" % (x, y, z - 1 if x >= 128 else z))
        w("\t" + ", ".join(row) + ",")
    w("};")
    w("")
    w("static const u32 s_apBoxFramedCommands[] = {")
    w("\tAP_BOX_FRAMED_NUM_COLORS,")
    for i, (_, _, ci) in enumerate(tris):
        ti = i + 1
        w("\t0x%08xu, 0x%08xu, 0x%08xu," % (0x80010000 | ti | (ci << 9), 0x00020000 | ti | (ci << 9),
                                           0x00030000 | ti | (ci << 9)))
    w("\t0xffffffffu,")
    w("};")
    w("")
    w("// One layout per triangle; corner k is strip vertex k. UVs are texel coordinates in the box sheet.")
    w("// Field order: u0, v0, clut, u1, v1, tpage, u2, v2, u3, v3.")
    w("static struct TextureLayout s_apBoxFramedLayouts[AP_BOX_FRAMED_NUM_TRIS] = {")
    for _, uvs, _ in tris:
        (u0, v0), (u1, v1), (u2, v2) = uvs
        w("\t{%3d,%3d, 0x%04x, %3d,%3d, 0x%04x, %3d,%3d, %3d,%3d}," % (u0, v0, CLUT, u1, v1, TPAGE, u2, v2, u2, v2))
    w("};")
    open(out, "w").write("\n".join(lines) + "\n")
    print("wrote", out, len(tris), "triangles")


if __name__ == "__main__":
    main(sys.argv[1])
