#!/usr/bin/env python3
"""Generate ap/ap_box_logo_mask_data.h: which pixels of the 64x64 AP box face
(box_pink_highres_inner.png, JurnthReinal) belong to the Archipelago logo.

The logo is the six circles and their dark outline. Everything else on the
face is background: the light pink field, the bevel along the edges and the
magenta filler column and row. The background is found by a flood fill from the
face's border that crosses every pixel brighter than LUMA_WALL and stops at the
dark outline around the circles, so the circles and their outline stay logo.

At runtime the client puts a recoloured retail crate face (read from the
player's disc) behind the logo: logo pixels keep JurnthReinal's art, background
pixels take the crate. The mask is data derived from JurnthReinal's art only; it
carries no retail pixels. Same attribution as the face (see README).

    python gen_logo_mask.py ../../ap/ap_box_logo_mask_data.h
"""
import sys
from collections import deque
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from convert import read_png  # noqa: E402

LUMA_WALL = 70
SRC = Path(__file__).resolve().parent / "box_pink_highres_inner.png"


def main(out):
    w, h, rgba = read_png(SRC)
    assert (w, h) == (64, 64), (w, h)
    luma = [(77 * rgba[i * 4] + 150 * rgba[i * 4 + 1] + 29 * rgba[i * 4 + 2]) >> 8 for i in range(w * h)]
    bg = [False] * (w * h)
    q = deque(i for i in range(w * h) if i % w in (0, w - 1) or i // w in (0, h - 1))
    while q:
        i = q.popleft()
        if bg[i] or luma[i] < LUMA_WALL:
            continue
        bg[i] = True
        x, y = i % w, i // w
        for nx, ny in ((x + 1, y), (x - 1, y), (x, y + 1), (x, y - 1)):
            if 0 <= nx < w and 0 <= ny < h and not bg[ny * w + nx]:
                q.append(ny * w + nx)
    rows = []
    for y in range(h):
        row = bytearray(8)
        for x in range(w):
            if not bg[y * w + x]:
                row[x >> 3] |= 1 << (x & 7)
        rows.append(row)
    logo = sum(not b for b in bg)
    lines = [
        "// GENERATED by tools/apbox-texture/gen_logo_mask.py -- do not edit by hand.",
        "//",
        "// Logo pixels of box_pink_highres_inner.png (JurnthReinal): bit x&7 of byte",
        "// [y][x>>3] is 1 where the six Archipelago circles or their outline are.",
        "// %d of 4096 pixels are logo." % logo,
        "",
        "#ifndef AP_BOX_LOGO_MASK_DATA_H",
        "#define AP_BOX_LOGO_MASK_DATA_H",
        "",
        "static const unsigned char s_apBoxLogoMask[64 * 8] = {",
    ]
    for row in rows:
        lines.append("\t" + ", ".join("0x%02x" % b for b in row) + ",")
    lines += ["};", "", "#endif // AP_BOX_LOGO_MASK_DATA_H", ""]
    Path(out).write_text("\n".join(lines))
    print("wrote", out, logo, "logo pixels")


if __name__ == "__main__":
    main(sys.argv[1])
