// The stand-in crystal for CTR progression rewards (#219).
//
// Built the same way as the #124 marker (ap_marker_model.c): a plain C aggregate
// on a 32-bit target produces a byte-identical struct Model the render path can
// consume, so there is no file IO, no pointer-map fixup and no shipped asset.
// The geometry is this project's own, generated by tools/apcrystal/convert.py --
// see that file for why it is not the retail arena crystal.
//
// WHAT THIS FIXES. Stef's own progression rewards rendered as fallback bars on a
// hub warp pad in game on 2026-08-12, at this branch's head. The cause was a
// display policy that decided a reward keeps its own model from the CATEGORY
// alone, while gGT->modelPtr[] is refilled per level: the crystal was not
// resident on the surface being drawn, the swap silently no-opped, and the slot
// kept whatever it had. The branch then tried to fix it by ASSERTING residency
// from which asset pack the hub runs, and got the pack wrong (the hub sets
// ADVENTURE_ARENA at LOAD_TenStages.c:161-166, so LOAD_DriverMPK takes the
// BI_ADVENTUREPACK branch at LOAD_Assets.c:118-130, not the 1P arcade branch).
//
// The lesson (Lessons Learned §24) is that a display resolver must be able to
// ask whether a model exists on the surface being drawn. This module answers a
// stronger version of that question: it MAKES the answer yes, everywhere, by
// owning a crystal of its own. Nothing here reasons about asset packs.

#ifdef CTR_AP

#include <common.h>

#include "ap_crystal_model.h"
#include "ap_crystal_model_data.h"

// The vertex bytes must sit immediately after the frame header, because the
// engine finds them at (char *)frame + frame->vertexOffset
// (namespace_Instance.h:301, read at RenderBucket_QueueExecute.c:5283).
struct ApCrystalFrame
{
	struct ModelFrame frame;
	u8                verts[AP_CRYSTAL_NUM_VERTS * 3];
};

CTR_STATIC_ASSERT(sizeof(struct ModelFrame) == 0x1c);
CTR_STATIC_ASSERT(offsetof(struct ApCrystalFrame, verts) == 0x1c);

// Not const: the engine's pointer fields are non-const and the frame origin is
// written once at registration.
static struct ApCrystalFrame s_apCrystalFrame;
static struct ModelHeader    s_apCrystalHeader;
static struct Model          s_apCrystalModel;
static int                   s_apCrystalBuilt;

// Fallback model scale, used only if STATIC_GEM is not loaded when we build.
// Vanilla model scales live in BIGFILE data, not in this repo, so this number is
// a guess; the gem-derived path below avoids relying on it.
#define AP_CRYSTAL_FALLBACK_SCALE 0x1000

static void AP_CrystalModel_Build(struct GameTracker *gGT)
{
	int i;

	// Vertices are byte coordinates in a 0..255 cube, so the model would hang off
	// the +octant of the instance origin. The frame origin recentres it. Pairing
	// (RenderBucket_QueueExecute.c:2237-2244, :2264): pos.x offsets vertex byte0
	// (horizontal), pos.y offsets byte2 (vertical), pos.z offsets byte1 (depth).
	s_apCrystalFrame.frame.pos.x = -128;
	s_apCrystalFrame.frame.pos.y = -128;
	s_apCrystalFrame.frame.pos.z = -128;
	s_apCrystalFrame.frame.vertexOffset = 0x1c;
	for (i = 0; i < AP_CRYSTAL_NUM_VERTS * 3; i++)
		s_apCrystalFrame.verts[i] = s_apCrystalVerts[i];

	s_apCrystalHeader.name[0] = 'a';
	s_apCrystalHeader.name[1] = 'p';
	s_apCrystalHeader.name[2] = 'c';
	s_apCrystalHeader.name[3] = '\0';
	// Win the LOD walk at every distance: the walk picks this header while
	// projectedDistance < (u16)maxDistanceLOD (QueueExecute.c:1283-1287), and
	// running out of headers means the model is not drawn at all (:1298-1300).
	s_apCrystalHeader.maxDistanceLOD = 0x7fff;
	s_apCrystalHeader.flags = 0;
	s_apCrystalHeader.ptrCommandList = (u32)(uintptr_t)s_apCrystalCommands;
	s_apCrystalHeader.ptrFrameData = &s_apCrystalFrame.frame;
	// NULL is legal only because every command's texture index is 0; a non-zero
	// index with no layout table would invalidate the prim (:2784-2805). It is
	// also what keeps this model on the plain POLY_G3 writer, which is the whole
	// reason AP_CrystalModel_IsStandIn exists -- see the header.
	s_apCrystalHeader.ptrTexLayout = 0;
	s_apCrystalHeader.ptrColors = (u32 *)(uintptr_t)s_apCrystalColors;
	// Both must stay zero: unk3 doubles as ptrDeltaArray and would send the
	// decoder down the bit-stream delta path instead of reading plain bytes
	// (:2398-2417); a non-null ptrAnimations would deselect ptrFrameData (:1956).
	s_apCrystalHeader.unk3 = 0;
	s_apCrystalHeader.numAnimations = 0;
	s_apCrystalHeader.ptrAnimations = 0;
	s_apCrystalHeader.animtex = 0;

	// Size the crystal off the gem, for the same reason the marker does: vanilla
	// model scales are not in this repo (they live in BIGFILE data), so deriving
	// beats inventing. The gem is the closest vanilla pad reward in bulk, and it
	// is the model the pad's own default scale block already sizes for.
	{
		struct Model *gem = gGT->modelPtr[STATIC_GEM];
		s16           s = AP_CRYSTAL_FALLBACK_SCALE;

		if (gem != 0 && gem->headers != 0 && gem->numHeaders > 0)
			s = gem->headers[0].scale.x;

		s_apCrystalHeader.scale.x = s;
		s_apCrystalHeader.scale.y = s;
		s_apCrystalHeader.scale.z = s;
	}

	s_apCrystalModel.name[0] = 'a';
	s_apCrystalModel.name[1] = 'p';
	s_apCrystalModel.name[2] = 'c';
	s_apCrystalModel.name[3] = '\0';
	// The stand-in answers the SAME model id as the retail crystal on purpose:
	// AH_WarpPad_SpinRewards and the pad's scale block both switch on
	// model->id, so a private id would need every one of those sites taught about
	// it -- the kind of second seam Lessons Learned §5 warns about. The two are
	// told apart by pointer identity instead (AP_CrystalModel_IsStandIn), at the
	// one site where the difference actually matters: the prim writer.
	s_apCrystalModel.id = STATIC_CRYSTAL;
	s_apCrystalModel.numHeaders = 1;
	s_apCrystalModel.headers = &s_apCrystalHeader;

	s_apCrystalBuilt = 1;
}

void AP_CrystalModel_Register(struct GameTracker *gGT)
{
	if (gGT == 0)
		return;

	// The retail crystal wins wherever the level actually loaded it. Checking the
	// slot rather than the asset pack is what makes this correct on surfaces
	// nobody has enumerated: arenas, the garage, cutscenes, a track, a future hub
	// variant. There is no pack table here to get wrong.
	if (gGT->modelPtr[STATIC_CRYSTAL] != 0 &&
	    !AP_CrystalModel_IsStandIn(gGT->modelPtr[STATIC_CRYSTAL]))
		return;

	// Build once the gem is available, so the derived scale is real rather than
	// the fallback. Before that the slot simply stays empty and the glow keeps its
	// previous model -- the render site NULL-checks modelPtr already.
	if (!s_apCrystalBuilt)
	{
		if (gGT->modelPtr[STATIC_GEM] == 0)
			return;
		AP_CrystalModel_Build(gGT);
	}

	gGT->modelPtr[STATIC_CRYSTAL] = &s_apCrystalModel;
}

int AP_CrystalModel_IsBuilt(void)
{
	return s_apCrystalBuilt;
}

int AP_CrystalModel_IsStandIn(const struct Model *model)
{
	return model == &s_apCrystalModel;
}

#endif // CTR_AP
