// GENERATED by tools/apcrystal/convert.py -- do not edit by hand.
//
// An ORIGINAL faceted-gem mesh authored by this project. It is NOT the
// retail battle-arena crystal and carries none of its data: the retail
// model lives in arena LEV data, which this public repo cannot ship, and
// whose residency on the adventure hub cannot be assumed -- assuming it
// is exactly what failed Stef's in-game gate on 2026-08-12.
//
// This mesh stands in ONLY where the real crystal is not loaded, so a CTR
// progression reward reads as a spinning purple crystal on every surface
// rather than as a marker on some of them. See ap/ap_crystal_model.c.
//
// Untextured, like the #124 marker: its greys are lerped toward the
// crystal purple by colorRGBA + alphaScale on the plain prim path. The
// textured writers (DRAW_TRANSPARENT, USE_SPECULAR_LIGHT) bail at
// tex == 0 and would draw nothing at all.
//
// Every facet is emitted in BOTH windings: gte_nclip rejects by winding
// (QueueExecute.c:2691-2702) and the build machine has no display, so a
// wrong guess would be invisible and indistinguishable from success.

#define AP_CRYSTAL_NUM_VERTS 144
#define AP_CRYSTAL_NUM_TRIS  48
#define AP_CRYSTAL_NUM_COLORS 22

// Deduplicated per-vertex shaded greys, 0x00BBGGRR.
static const u32 s_apCrystalColors[AP_CRYSTAL_NUM_COLORS] = {
    0x009c9c9c, 0x00848484, 0x00a8a8a8, 0x00909090, 0x00a0a0a0, 0x00888888, 0x00b4b4b4, 0x00bcbcbc, 0x00a4a4a4, 0x00c8c8c8, 0x00787878, 0x00606060, 0x008c8c8c, 0x00545454, 0x00404040, 0x00686868, 0x007c7c7c, 0x00949494, 0x00b0b0b0, 0x00747474, 0x00c4c4c4, 0x00282828,
};

// Draw-order vertex bytes: byte0 = horizontal, byte1 = depth, byte2 = vertical.
static const u8 s_apCrystalVerts[AP_CRYSTAL_NUM_VERTS * 3] = {
    128,128,254, 255,128,170, 191,238,170, 128,128,254, 191,238,170, 255,128,170, 255,128,170, 222,182, 88,
    191,238,170, 255,128,170, 191,238,170, 222,182, 88, 191,238,170, 222,182, 88, 128,237, 88, 191,238,170,
    128,237, 88, 222,182, 88, 222,182, 88, 128,128,  0, 128,237, 88, 222,182, 88, 128,237, 88, 128,128,  0,
    128,128,254, 191,238,170,  64,238,171, 128,128,254,  64,238,171, 191,238,170, 191,238,170, 128,237, 88,
     64,238,171, 191,238,170,  64,238,171, 128,237, 88,  64,238,171, 128,237, 88,  33,182, 89,  64,238,171,
     33,182, 89, 128,237, 88, 128,237, 88, 128,128,  0,  33,182, 89, 128,237, 88,  33,182, 89, 128,128,  0,
    128,128,254,  64,238,171,   0,128,171, 128,128,254,   0,128,171,  64,238,171,  64,238,171,  33,182, 89,
      0,128,171,  64,238,171,   0,128,171,  33,182, 89,   0,128,171,  33,182, 89,  33, 73, 89,   0,128,171,
     33, 73, 89,  33,182, 89,  33,182, 89, 128,128,  0,  33, 73, 89,  33,182, 89,  33, 73, 89, 128,128,  0,
    128,128,254,   0,128,171,  64, 17,171, 128,128,254,  64, 17,171,   0,128,171,   0,128,171,  33, 73, 89,
     64, 17,171,   0,128,171,  64, 17,171,  33, 73, 89,  64, 17,171,  33, 73, 89, 127, 18, 89,  64, 17,171,
    127, 18, 89,  33, 73, 89,  33, 73, 89, 128,128,  0, 127, 18, 89,  33, 73, 89, 127, 18, 89, 128,128,  0,
    128,128,254,  64, 17,171, 191, 17,170, 128,128,254, 191, 17,170,  64, 17,171,  64, 17,171, 127, 18, 89,
    191, 17,170,  64, 17,171, 191, 17,170, 127, 18, 89, 191, 17,170, 127, 18, 89, 222, 73, 88, 191, 17,170,
    222, 73, 88, 127, 18, 89, 127, 18, 89, 128,128,  0, 222, 73, 88, 127, 18, 89, 222, 73, 88, 128,128,  0,
    128,128,254, 191, 17,170, 255,128,170, 128,128,254, 255,128,170, 191, 17,170, 191, 17,170, 222, 73, 88,
    255,128,170, 191, 17,170, 255,128,170, 222, 73, 88, 255,128,170, 222, 73, 88, 222,182, 88, 255,128,170,
    222,182, 88, 222, 73, 88, 222, 73, 88, 128,128,  0, 222,182, 88, 222, 73, 88, 222,182, 88, 128,128,  0,
};

// [0] = colour count (copied to the scratchpad colour cache), then one
// command per vertex, then the 0xffffffff terminator.
static const u32 s_apCrystalCommands[] = {
    AP_CRYSTAL_NUM_COLORS,
    0x80010000, 0x00020200, 0x00030200, 0x80010000, 0x00020200, 0x00030200,
    0x80010400, 0x00020600, 0x00030400, 0x80010400, 0x00020400, 0x00030600,
    0x80010800, 0x00020a00, 0x00030a00, 0x80010800, 0x00020a00, 0x00030a00,
    0x80010000, 0x00020200, 0x00030000, 0x80010000, 0x00020000, 0x00030200,
    0x80010c00, 0x00020800, 0x00030800, 0x80010c00, 0x00020800, 0x00030800,
    0x80010e00, 0x00021000, 0x00030e00, 0x80010e00, 0x00020e00, 0x00031000,
    0x80011200, 0x00020c00, 0x00030c00, 0x80011200, 0x00020c00, 0x00030c00,
    0x80011400, 0x00021600, 0x00031400, 0x80011400, 0x00021400, 0x00031600,
    0x80011000, 0x00021800, 0x00031800, 0x80011000, 0x00021800, 0x00031800,
    0x80010800, 0x00021800, 0x00030800, 0x80010800, 0x00020800, 0x00031800,
    0x80011a00, 0x00021c00, 0x00031c00, 0x80011a00, 0x00021c00, 0x00031c00,
    0x80011e00, 0x00021a00, 0x00031e00, 0x80011e00, 0x00021e00, 0x00031a00,
    0x80010600, 0x00022000, 0x00032000, 0x80010600, 0x00022000, 0x00032000,
    0x80012200, 0x00022000, 0x00032200, 0x80012200, 0x00022200, 0x00032000,
    0x80011200, 0x00022400, 0x00032400, 0x80011200, 0x00022400, 0x00032400,
    0x80012600, 0x00021600, 0x00032600, 0x80012600, 0x00022600, 0x00031600,
    0x80012800, 0x00022400, 0x00032400, 0x80012800, 0x00022400, 0x00032400,
    0x80011200, 0x00020c00, 0x00031200, 0x80011200, 0x00021200, 0x00030c00,
    0x80011000, 0x00020600, 0x00030600, 0x80011000, 0x00020600, 0x00030600,
    0x80010800, 0x00021800, 0x00030800, 0x80010800, 0x00020800, 0x00031800,
    0x80011800, 0x00022600, 0x00032600, 0x80011800, 0x00022600, 0x00032600,
    0x80010000, 0x00020200, 0x00030000, 0x80010000, 0x00020000, 0x00030200,
    0x80011400, 0x00021600, 0x00031600, 0x80011400, 0x00021600, 0x00031600,
    0x80011c00, 0x00022a00, 0x00031c00, 0x80011c00, 0x00021c00, 0x00032a00,
    0xffffffffu,
};
