#ifndef AP_SEEDCFG_H
#define AP_SEEDCFG_H
#ifdef CTR_AP

// Per-seed slot_data configuration for CTR-Native (Phase 2-MVP).
//
// apclientpp surfaces slot_data as nlohmann::json on the network thread inside
// poll(); ap_net.cpp's Connected handler calls ap_seedcfg_parse_json() to fill
// the C-accessible ctr_cfg struct below. The C gate sites (game/232/AH_*.c)
// read ctr_cfg + the helpers through this header (pulled in via ap_hooks.h ->
// game_includes.h), gated on schema_version. When schema_version stays 0 (no
// slot_data, or schema absent / < 1) every gate falls back to its Phase-1
// static rule -- the parser never partially-activates because schema_version is
// written LAST, after all fields are populated.
//
// Thread-safety: ctr_cfg is written on the network thread inside poll() and read
// on the game thread in the SAME ap_net_poll() call (apclientpp is
// single-threaded -- the same guarantee the received-item queue relies on). No
// lock needed.

#ifdef __cplusplus
extern "C" {
#endif

// 28 physical warp-pad LevelIDs (0..27 covers the §0 track + arena IDs we index
// through the dense arrays). CupRed..CupPurple are LevelID 100..104 and live
// OUTSIDE these 28-wide arrays: their per-seed unlock is in gem_cup_unlock[5] and
// (slot_data v3, destination-shuffle categories) their per-seed destination is in
// gem_cup_map[5]. Under `merged` grouping the shuffle ID space spans {0..27,
// 100..104} in BOTH directions -- a cup PHYSICAL pad may host any destination and
// any physical pad may host a cup destination -- so the warp_dest/warp_phys
// helpers below cover both arrays.
#define CTR_CFG_PAD_COUNT 28
#define CTR_CFG_BOSS_COUNT 5 // 0 roo, 1 papu, 2 komodo, 3 pinstripe, 4 oxide

// Highest slot_data schema_version this BUILD understands (issue #8). A seed
// carrying schema_version > this was generated by a NEWER apworld than this
// client: the parser cannot be sure it enforces every gate correctly, so it
// warns LOUDLY (stderr log + a persistent on-screen banner, ctr_cfg.schema_newer)
// instead of silently guessing. Bump this in lockstep with the apworld's
// fill_slot_data schema_version whenever the native side is taught the new shape.
//   5 = oxide_final_unlock relic-goal mode + oxide_final_count (issue #23)
//   4 = type-4 relic-tier colour + goal-rework; 3 = podium + stage-2 padgate;
//   2 = two-stage contract; 1 = flat pre-two-stage.
#define CTR_CFG_SCHEMA_KNOWN 5

// oxide_final_unlock relic-goal MODE (slot_data schema >= 5). Value 0 stays
// frozen = the pre-v0.1.1 "18 Sapphire" default. The shared count is in
// ctr_cfg.oxide_final_count (1..18). Relic tiers are INDEPENDENT items with no
// downward hierarchy -- these mirror the apworld FinalOxideUnlock option exactly.
#define OXIDE_FINAL_MODE_SAPPHIRE 0 // N Sapphire Relic items
#define OXIDE_FINAL_MODE_GOLD     1 // N Gold Relic items
#define OXIDE_FINAL_MODE_PLATINUM 2 // N Platinum Relic items
#define OXIDE_FINAL_MODE_ANY      3 // any single tier reaches N
#define OXIDE_FINAL_MODE_TOTAL    4 // Sapphire + Gold + Platinum summed reach N

// Podium placement checks (feat/podium-checks apworld side). The nested rung
// ladder rides ONLY the 16 standard adventure trophy races, keyed by physical
// race-pad LevelID 0..15 (== gGT->levelID at a trophy race == the [AP RACE]
// track field the listener logs). Boss/token/relic/crystal have no genuine
// multi-position finish and carry no podium rungs.
#define CTR_CFG_PODIUM_TRACK_COUNT 16

// One resolved requirement. type per the §0 shared table:
//   0 none/use native vanilla fixed rule
//   1 trophies   2 keys   3 tokens   4 sapphire   5 gems
//   6 AnyToken   7 AnyRelic   8 AnyGem   (any-of aggregates, colour = -1)
// colour: -1 (n/a) or 0..4 = R,G,B,Y,P (only meaningful for tokens / gems).
//
// any-of semantics (requirement_specificity = any_of, the apworld default):
//   type 3 token / 5 gem with colour 0..4 = a SPECIFIC colour; colour -1 = the
//     legacy single-colour defensive fallback (apworld never emits it under any_of).
//   type 6 AnyToken  (colour -1) = owned >= count summed over ALL 5 token colours.
//   type 7 AnyRelic  (colour -1) = owned >= count summed over Sapphire+Gold+Platinum.
//   type 8 AnyGem    (colour -1) = owned >= count summed over ALL 5 gem colours.
// See AP_BossReqMet (ap_hooks.c) + AP_GateCount*Sum (ap_hooks.{h,c}).
typedef struct
{
	int type;
	int count;
	int colour;
} ctr_req;

// One trophy race's podium rungs, as AP location codes (NOT AdvProgress bits --
// the game has no bit for "finished 2nd", so these fire event-only from the
// placement listener, never through AP_NotifyAdvReward's bit lookup). A rung
// absent from the seed (any-position off, or the whole feature off) is stored
// as -1 and MUST be skipped by the native fan-out.
typedef struct
{
	long first;  // "Finish 1st"          location code, or -1 = absent
	long podium; // "Finish 2nd or 3rd"   location code, or -1 = absent
	long any;    // "Finish (Any Position)" location code, or -1 = absent
} ctr_podium_rungs;

// Two-stage warp-pad unlock (open-rando). stage1 opens the trophy race; stage2
// opens the relic Time Trials + CTR Token Challenge menu. Each stage is an
// independent resolved requirement that can be ANY CTR item type (relic/trophy/
// gem/token/key). A pad's stage2 MAY equal stage1 when a seed collapses it.
// schema_version 1 (flat, pre two-stage) is parsed into stage1 with a type:0
// (always-open) stage2 for back-compat -- see ap_seedcfg_parse_json.
typedef struct
{
	ctr_req stage1; // open the trophy race
	ctr_req stage2; // open the relic Time Trials + CTR Token Challenge
} ctr_warp_unlock;

typedef struct
{
	int schema_version; // 0 = not parsed -> Phase-1 fallback everywhere
	// Set when the parsed schema_version exceeds CTR_CFG_SCHEMA_KNOWN (issue #8):
	// the seed is from a newer apworld than this build. Drives the loud on-screen
	// "update the client" banner. Reset to 0 at the top of every parse.
	int schema_newer;

	int goal;
	int relic_min_time;
	int relics_require_perfect;
	// Oxide's Final Challenge gate. schema >= 5: oxide_final_unlock is a relic-goal
	// MODE (OXIDE_FINAL_MODE_*) and oxide_final_count (1..18) is the shared count.
	// 0 = Sapphire stays frozen = the pre-v0.1.1 default. See AP_OxideFinalOpen.
	int oxide_final_unlock; // relic-goal mode (0 sapphire..4 total)
	int oxide_final_count;  // relics required (1..18); default 18
	int shuffle_warp_pads;
	int warppad_unlock_mode; // 0 vanilla / 1 random / 2 random_without_4_keys
	int bossgarage_mode;     // 0 original4 / 1 same_hub / 2 trophies
	// item #5 placement toggles (forward-looking; MVP native ignores them because
	// locked gems/keys never enter the multiworld pool -> native never receives an
	// item it must place). A future native build can branch on these to tell
	// "reward not shuffled" apart from "reward shuffled elsewhere".
	int shuffle_gems;        // 0 gems pinned to gem cups / 1 gems in the pool
	int shuffle_keys;        // 0 keys pinned to boss races / 1 keys in the pool

	// AI-difficulty preset (option-sync pattern). OPTIONAL field: the apworld may put
	// a starting value in ctr_options.ai_difficulty, but generation NEVER depends on
	// it, so its absence needs no schema bump. -1 = "no slot_data default" (the seed
	// did not set it); otherwise the raw engine difficulty VALUE (0 = vanilla; presets
	// 0x50/0xA0/0xF0/0x140/0x280) the connect-time pull seeds into the local value
	// before the per-slot data-storage override (key "ctr_difficulty_<slot>") is
	// fetched. An out-of-ladder value is applied as-is.
	int ai_difficulty_default;

	// QoL: one-lap cup races (slot_data ctr_options.one_lap_cups). Pure pace
	// setting -- when 1, CUP races (gameMode2 & CUP_ANY_KIND) run a single lap
	// via the vanilla one-lap mechanism; single/boss/trial races are untouched.
	// ADDITIVE, no schema bump: json_int defaults the absent key to 0 (vanilla),
	// so it never affects reachability and needs no version gate.
	int one_lap_cups;       // 0 vanilla lap counts / 1 cups are one lap

	int             warp_pad_map[CTR_CFG_PAD_COUNT];    // physical pad LevelID -> target trackID (identity default)
	ctr_warp_unlock warp_pad_unlock[CTR_CFG_PAD_COUNT]; // per-pad two-stage resolved reqs (stage1.type 0 = native vanilla rule)
	// Gem cups (CupRed..CupPurple = LevelID 100..104) live OUTSIDE the 28-wide
	// warp_pad_unlock array, so their per-seed randomized unlock requirement is
	// stored here, keyed by cup colour 0..4 = R,G,B,Y,P (= LevelID - 100). The
	// apworld emits these under the same warp_pad_unlock object using string keys
	// "100".."104"; the parser routes those keys into this array. stage1.type 0 =
	// fall back to the Phase-1 "4 tokens of this colour" rule. stage2 unused (gem
	// cups have no tier-2 menu); kept as ctr_warp_unlock only for parse symmetry.
	ctr_warp_unlock gem_cup_unlock[5];                  // gem cups by colour (LevelID 100..104); stage1.type 0 = native vanilla rule
	// slot_data v3 (destination-shuffle categories): the destination LevelID that
	// physical cup pad 100+i LOADS, keyed by cup colour 0..4 (= LevelID - 100).
	// Identity default (gem_cup_map[i] == 100 + i) until warp_pad_map overlays it,
	// exactly like warp_pad_map's identity base for 0..27. Under `merged` grouping a
	// value here may be ANY {0..27, 100..104} (a cup pad hosting a race/arena/other
	// cup); ctr_cfg_warp_dest/ctr_cfg_warp_phys read this array alongside
	// warp_pad_map so the phys<->dest mapping is a single permutation over the union.
	int             gem_cup_map[5];                     // phys cup LevelID 100+i -> destination LevelID (identity default 100+i)
	ctr_req         boss_req[CTR_CFG_BOSS_COUNT];       // 0 roo,1 papu,2 komodo,3 pinstripe,4 oxide
	// Per-boss required race-track LevelIDs for the track-based garage modes
	// (bossgarage_mode 0 Original4Tracks / 1 SameHubTracks). boss_tracks[b][0..
	// boss_n_tracks[b]-1] are the LevelIDs the player must have WON for boss b to
	// open; n==0 / entry -1 = no track list (mode 2 Trophies, or Oxide) -> use
	// boss_req. Emitted by the apworld under boss_garage_req[<boss>].tracks.
	int             boss_tracks[CTR_CFG_BOSS_COUNT][4];
	int             boss_n_tracks[CTR_CFG_BOSS_COUNT];

	// Podium placement checks (feat/podium-checks). enabled/any_position mirror
	// the two apworld toggles; podium[levelID] holds the per-track rung codes for
	// the 16 trophy races. The native fan-out (ap_hooks.c AP_RaceListenerTick)
	// reads these at the finish-line capture point. Additive block -- absent from
	// pre-podium seeds, in which case podium_enabled stays 0 and no rung fires.
	int              podium_enabled;      // podium_checks.enabled
	int              podium_any_position; // podium_checks.any_position
	ctr_podium_rungs podium[CTR_CFG_PODIUM_TRACK_COUNT]; // by trophy-race LevelID 0..15
} ctr_seed_config;

// Global config, zero-init; schema_version == 0 until ap_seedcfg_parse_json runs.
extern ctr_seed_config ctr_cfg;

// schema_version >= 1 (slot_data parsed and active).
int ctr_cfg_active(void);

// Remapped destination trackID for a physical pad LevelID. Accepts the full
// shuffle ID space: physical pads 0..27 (warp_pad_map) and cup pads 100..104
// (gem_cup_map). Identity (returns the input unchanged) when inactive or out of
// range -- safe to call unconditionally.
int ctr_cfg_warp_dest(int physPadLevelID);

// Inverse of ctr_cfg_warp_dest: given the destination trackID a pad currently
// LOADS (warppadObj->levelID after the LInB remap), return the PHYSICAL pad
// LevelID. Scans BOTH warp_pad_map (0..27) and gem_cup_map (100..104), so the
// destination (and the recovered physical pad) may be anywhere in {0..27,
// 100..104}. Identity (returns the input unchanged) when inactive, out of range,
// or when no pad maps to that destination. Used by AH_WarpPad_ThTick's load gate
// so the per-pad unlock requirement (keyed by PHYSICAL pad) is checked against
// the physical pad and not the remapped destination. The union of the two maps is
// a permutation over the participating pool, so the inverse is unique.
int ctr_cfg_warp_phys(int destTrackLevelID);

// Is a warp pad's stage-1 LOAD gate satisfied? levelID is the PHYSICAL pad. When
// active and the pad has a per-seed requirement (type != 0), compares owned >=
// count for that requirement (colour-aware for tokens/gems). Otherwise falls back
// to that pad class's Phase-1 rule. Accepts BOTH the dense-array pads (0..27,
// vanilla fallback = received trophies >= numTrophiesToOpen) and cup pads
// (100..104 -> gem_cup_unlock[phys-100], vanilla fallback = 4 tokens of the cup's
// colour) -- required because under destination shuffle a race destination can be
// hosted on a cup PHYSICAL pad, and ThTick's load gate then calls this with a
// physical cup LevelID. Used by the load-time gate in AH_WarpPad_ThTick so the
// spawn visual and the load gate read one source.
//
// IMPLEMENTED C-SIDE in ap_hooks.c (not ap_seedcfg.cpp): it needs AP_GateCount*
// (received-item counters live in the C unity build) and the per-track
// numTrophiesToOpen threshold from data.metaDataLEV[] for the Phase-1 fallback,
// neither of which is reachable from the isolated C++ static lib.
int ctr_cfg_warp_unlocked(int levelID);

// Is a trophy-track warp pad's STAGE-2 satisfied (open the relic Time Trials +
// CTR Token Challenge menu)? When active and the pad has a stage2 requirement
// (type != 0), compares owned >= count for stage2 (colour-aware for tokens/gems
// via AP_BossReqMet). type 0 (no stage2 / collapsed / flat-v1 slot_data) returns
// 1 (always open) so the tier-2 menu opens as soon as stage1 is met -- exactly
// the pre-two-stage behaviour. physPadLevelID is the PHYSICAL pad LevelID, the
// same key ctr_cfg_warp_unlocked uses. Accepts cup pads 100..104
// (-> gem_cup_unlock[phys-100].stage2): under `merged` shuffle a cup PHYSICAL pad
// can host a trophy-race destination, which per the contract §2 stage-2 rule
// carries a real stage2, so the cup pad's stage2 must be honoured here.
// IMPLEMENTED C-SIDE in ap_hooks.c.
int ctr_cfg_warp_stage2_unlocked(int physPadLevelID);

// The stage-2 requirement record for a physical pad, or NULL when it has none
// (type 0 / invalid id / slot_data inactive). Single source for the stage-2
// key logic: dense pads 0..27 via warp_pad_unlock, cup pads 100..104 via
// gem_cup_unlock. ctr_cfg_warp_stage2_unlocked and the LInB re-lock advert
// both resolve through it. IMPLEMENTED C-SIDE in ap_hooks.c.
const ctr_req *ctr_cfg_warp_stage2_req(int physPadLevelID);

// Typed comparator for a resolved requirement (boss garages + warp-pad load
// gate). Returns owned >= count for r->type using AP_GateCount* (colour-aware).
// type 0 / unknown -> 1 (no requirement). IMPLEMENTED C-SIDE in ap_hooks.c.
int AP_BossReqMet(const ctr_req *r);

// Per-mode boss-garage gate for the four boss hubs (bossIdx 0..3 = Roo, Papu,
// Komodo, Pinstripe). Honours bossgarage_mode: modes 0/1 (Original4Tracks /
// SameHubTracks) open the garage once every required race track for that boss
// has been WON (boss_tracks[bossIdx]); mode 2 (Trophies) and any boss with no
// track list fall back to the flat trophy-count requirement via AP_BossReqMet.
// IMPLEMENTED C-SIDE in ap_hooks.c (needs AP_LocationCheckedByBit).
int AP_BossGarageOpen(int bossIdx);

#ifdef __cplusplus
} // extern "C"

#include <nlohmann/json.hpp>
// C++-only: parse the slot_data JSON into ctr_cfg. Called from ap_net.cpp.
void ap_seedcfg_parse_json(const nlohmann::json &j);
#endif

#endif // CTR_AP
#endif // AP_SEEDCFG_H
