#ifndef AP_SEEDCFG_H
#define AP_SEEDCFG_H
#ifdef CTR_AP

// Per-seed slot_data configuration for CTR-Native (Phase 2-MVP).
//
// apclientpp surfaces slot_data as nlohmann::json on the network thread inside
// poll(); ap_net.cpp's Connected handler calls ap_seedcfg_parse_json() to fill
// the C-accessible ctr_cfg struct below. The C gate sites (game/232/AH_*.c)
// read ctr_cfg + the helpers through this header (pulled in via ap_hooks.h ->
// game_includes.h), gated on schema_version. When schema_version stays 0 (no
// slot_data, or schema absent / < 1) every gate falls back to its Phase-1
// static rule -- the parser never partially-activates because schema_version is
// written LAST, after all fields are populated.
//
// Thread-safety: ctr_cfg is written on the network thread inside poll() and read
// on the game thread in the SAME ap_net_poll() call (apclientpp is
// single-threaded -- the same guarantee the received-item queue relies on). No
// lock needed.

#ifdef __cplusplus
extern "C" {
#endif

// 28 physical warp-pad LevelIDs (0..27 covers the §0 track + arena IDs we index
// through the dense arrays). CupRed..CupPurple are LevelID 100..104 and live
// OUTSIDE these 28-wide arrays: their per-seed unlock is in gem_cup_unlock[5] and
// (slot_data v3, destination-shuffle categories) their per-seed destination is in
// gem_cup_map[5]. Under `merged` grouping the shuffle ID space spans {0..27,
// 100..104} in BOTH directions -- a cup PHYSICAL pad may host any destination and
// any physical pad may host a cup destination -- so the warp_dest/warp_phys
// helpers below cover both arrays.
#define CTR_CFG_PAD_COUNT 28
#define CTR_CFG_BOSS_COUNT 5 // 0 roo, 1 papu, 2 komodo, 3 pinstripe, 4 oxide

// Buffer for ctr_options.world_version (issue #150). "A.B.C[.D]" needs a dozen
// bytes; 32 leaves room for anything sane and the parser truncates rather than
// overruns. A truncated value simply fails to parse -> the notice stays silent.
#define CTR_CFG_VERSION_CAP 32

// Highest slot_data schema_version this BUILD understands (issue #8). A seed
// carrying schema_version > this was generated by a NEWER apworld than this
// client: the parser cannot be sure it enforces every gate correctly, so it
// warns LOUDLY (stderr log + a persistent on-screen banner, ctr_cfg.schema_newer)
// instead of silently guessing. Bump this in lockstep with the apworld's
// fill_slot_data schema_version whenever the native side is taught the new shape.
//   7 = gem cup leg randomization, gem_cup_legs[5][4] (issue #166). The bump is
//       UNCONDITIONAL on the apworld side (Q28 ruling) -- every 0.2.0 seed
//       declares 7, on or off, so a pre-7 client warns on every new seed.
//       Issue #152 (composed goal conditions: goal_oxide/goal_bosses/
//       goal_gems) rides this SAME 7, additive, no further bump -- every
//       0.2.0 seed already declares 7 regardless of #166, so a client that
//       understands 7 already knows to read the composed fields instead of
//       the legacy `goal` int, and a pre-7 client already shows the #8
//       banner and (issue #163) already suppresses auto-GOAL on schema_newer.
//   6 = 5-rung podium rework (held 1st/3rd/5th live + finish podium/any); #9
//   5 = oxide_final_unlock relic-goal mode + oxide_final_count (issue #23)
//   4 = type-4 relic-tier colour + goal-rework; 3 = podium + stage-2 padgate;
//   2 = two-stage contract; 1 = flat pre-two-stage.
#define CTR_CFG_SCHEMA_KNOWN 7

// oxide_final_unlock relic-goal MODE (slot_data schema >= 5). Value 0 stays
// frozen = the pre-v0.1.1 "18 Sapphire" default. The shared count is in
// ctr_cfg.oxide_final_count (1..18). Relic tiers are INDEPENDENT items with no
// downward hierarchy -- these mirror the apworld FinalOxideUnlock option exactly.
#define OXIDE_FINAL_MODE_SAPPHIRE 0 // N Sapphire Relic items
#define OXIDE_FINAL_MODE_GOLD     1 // N Gold Relic items
#define OXIDE_FINAL_MODE_PLATINUM 2 // N Platinum Relic items
#define OXIDE_FINAL_MODE_ANY      3 // any single tier reaches N
#define OXIDE_FINAL_MODE_TOTAL    4 // Sapphire + Gold + Platinum summed reach N

// warp_pad_item_display (issue #59, apworld option WarpPadItemDisplay). Pure
// DISPLAY setting for the pad reward glow -- it steers no gate, no location and
// no item. Value 0 stays frozen = the pile the glow has always shown.
#define WARP_PAD_DISPLAY_ONE_PILE       0 // all uncollected items share the 3 slots
#define WARP_PAD_DISPLAY_BY_REWARD_TYPE 1 // one slot per reward type, rotating within it

// Podium placement checks (feat/podium-checks apworld side). The rung ladder
// rides ONLY the 16 standard adventure trophy races, keyed by physical race-pad
// LevelID 0..15 (== gGT->levelID at a trophy race == the [AP RACE] track field
// the listener logs). Boss/token/relic/crystal have no genuine multi-position
// finish and carry no podium rungs. Cup legs are real track loads on these same
// LevelIDs and classify as trophy races, so they earn the destination track's
// rungs too (the held listener + finish fan-out run during cup legs).
#define CTR_CFG_PODIUM_TRACK_COUNT 16

// Number of podium rungs per track (schema >= 6). The nested ladder, best-first:
//   0 held_1st       -- live: held 1st place  (grants held_3rd + held_5th)
//   1 held_3rd       -- live: held 3rd or better (grants held_5th)
//   2 held_5th       -- live: held 5th or better (ships default-OFF; pool lever)
//   3 finish_podium  -- final: finished on the podium (top 3) (grants finish_any)
//   4 finish_any     -- final: finished at all
// The retired "Finish 1st" rung (schema <= 5) is gone from creation -- the trophy
// check already covers a 1st-place finish -- so it carries no slot here.
#define CTR_CFG_PODIUM_RUNG_COUNT 5

// One resolved requirement. type per the §0 shared table:
//   0 none/use native vanilla fixed rule
//   1 trophies   2 keys   3 tokens   4 sapphire   5 gems
//   6 AnyToken   7 AnyRelic   8 AnyGem   (any-of aggregates, colour = -1)
// colour: -1 (n/a) or 0..4 = R,G,B,Y,P (only meaningful for tokens / gems).
//
// any-of semantics (requirement_specificity = any_of, the apworld default):
//   type 3 token / 5 gem with colour 0..4 = a SPECIFIC colour; colour -1 = the
//     legacy single-colour defensive fallback (apworld never emits it under any_of).
//   type 6 AnyToken  (colour -1) = owned >= count summed over ALL 5 token colours.
//   type 7 AnyRelic  (colour -1) = owned >= count summed over Sapphire+Gold+Platinum.
//   type 8 AnyGem    (colour -1) = owned >= count summed over ALL 5 gem colours.
// See AP_BossReqMet (ap_hooks.c) + AP_GateCount*Sum (ap_hooks.{h,c}).
typedef struct
{
	int type;
	int count;
	int colour;
} ctr_req;

// One trophy race's podium rungs, as AP location codes (NOT AdvProgress bits --
// the game has no bit for "held 3rd" or "finished 2nd", so these fire event-only
// from the placement listener, never through AP_NotifyAdvReward's bit lookup). A
// rung absent from the seed (held_5th default-off, a rung the seed did not place,
// or the whole feature off) is stored as -1 and MUST be skipped by the fan-out.
// Order matches CTR_CFG_PODIUM_RUNG_COUNT above; the held_* rungs are LIVE
// (mid-race, from the position listener), the finish_* rungs are FINAL (captured
// at the finish edge). schema <= 5 seeds carry the legacy {first, podium, any}
// shape: podium -> finish_podium, any -> finish_any, first retired, held_* absent.
typedef struct
{
	long held_1st;      // live "held 1st place"        location code, or -1 = absent
	long held_3rd;      // live "held 3rd or better"    location code, or -1 = absent
	long held_5th;      // live "held 5th or better"    location code, or -1 = absent
	long finish_podium; // final "finished on podium"   location code, or -1 = absent
	long finish_any;    // final "finished (any place)" location code, or -1 = absent
} ctr_podium_rungs;

// Two-stage warp-pad unlock (open-rando). stage1 opens the trophy race; stage2
// opens the relic Time Trials + CTR Token Challenge menu. Each stage is an
// independent resolved requirement that can be ANY CTR item type (relic/trophy/
// gem/token/key). A pad's stage2 MAY equal stage1 when a seed collapses it.
// schema_version 1 (flat, pre two-stage) is parsed into stage1 with a type:0
// (always-open) stage2 for back-compat -- see ap_seedcfg_parse_json.
typedef struct
{
	ctr_req stage1; // open the trophy race
	ctr_req stage2; // open the relic Time Trials + CTR Token Challenge
} ctr_warp_unlock;

typedef struct
{
	int schema_version; // 0 = not parsed -> Phase-1 fallback everywhere
	// Set when the parsed schema_version exceeds CTR_CFG_SCHEMA_KNOWN (issue #8):
	// the seed is from a newer apworld than this build. Drives the loud on-screen
	// "update the client" banner. Reset to 0 at the top of every parse.
	int schema_newer;

	int goal; // issue #152: legacy field, best-effort/debug-only on a composed
	          // seed -- AP_EvaluateGoal and ap_verify.c read ONLY goal_oxide/
	          // goal_bosses/goal_gems below, never this. -1 = no legacy analogue.
	// Composed goal conditions (issue #152), ANDed together. At least one is
	// always active (the apworld's generate_early rejects the all-off
	// combination). 0 means "this condition is off" for all three, uniformly.
	int goal_oxide;  // 0 none / 1 first (Oxide's Challenge) / 2 final (Oxide's Final Challenge)
	int goal_bosses; // 0-4: how many of the 4 boss races must be personally won
	int goal_gems;   // 0-5: how many of the 5 Gems must be held
	int relic_min_time;
	int relics_require_perfect;
	// Oxide's Final Challenge gate. schema >= 5: oxide_final_unlock is a relic-goal
	// MODE (OXIDE_FINAL_MODE_*) and oxide_final_count (1..18) is the shared count.
	// 0 = Sapphire stays frozen = the pre-v0.1.1 default. See AP_OxideFinalOpen.
	int oxide_final_unlock; // relic-goal mode (0 sapphire..4 total)
	int oxide_final_count;  // relics required (1..18); default 18
	int shuffle_warp_pads;
	int warppad_unlock_mode; // 0 vanilla / 1 random / 2 random_without_4_keys
	int bossgarage_mode;     // 0 original4 / 1 same_hub / 2 trophies
	// item #5 placement toggles (forward-looking; MVP native ignores them because
	// locked gems/keys never enter the multiworld pool -> native never receives an
	// item it must place). A future native build can branch on these to tell
	// "reward not shuffled" apart from "reward shuffled elsewhere".
	int shuffle_gems;        // 0 gems pinned to gem cups / 1 gems in the pool
	int shuffle_keys;        // 0 keys pinned to boss races / 1 keys in the pool

	// AI-difficulty preset (option-sync pattern). OPTIONAL field: the apworld may put
	// a starting value in ctr_options.ai_difficulty, but generation NEVER depends on
	// it, so its absence needs no schema bump. -1 = "no slot_data default" (the seed
	// did not set it); otherwise the raw engine difficulty VALUE (0 = vanilla; presets
	// 0x50/0xA0/0xF0/0x140/0x280) the connect-time pull seeds into the local value
	// before the per-slot data-storage override (key "ctr_difficulty_<slot>") is
	// fetched. An out-of-ladder value is applied as-is.
	int ai_difficulty_default;

	// QoL: one-lap cup races (slot_data ctr_options.one_lap_cups). Pure pace
	// setting -- when 1, CUP races (gameMode2 & CUP_ANY_KIND) run a single lap
	// via the vanilla one-lap mechanism; single/boss/trial races are untouched.
	// ADDITIVE, no schema bump: json_int defaults the absent key to 0 (vanilla),
	// so it never affects reachability and needs no version gate.
	int one_lap_cups;       // 0 vanilla lap counts / 1 cups are one lap

	// Warp-pad reward glow layout (issue #59, slot_data ctr_options.
	// warp_pad_item_display). WARP_PAD_DISPLAY_*: 0 = every uncollected item
	// shares the three prize slots and they cycle through the whole pile
	// together; 1 = each reward type owns one slot and rotates only within its
	// own type. ADDITIVE, no schema bump (the one_lap_cups precedent): json_int
	// defaults the absent key to 0, which IS today's pile, so an old seed on a
	// new client and a new seed on an old client both glow exactly as they do
	// now. Display only -- never read by a gate, a check or an item.
	int warp_pad_item_display;

	// AP-item type colours (issue #212, slot_data ctr_options.
	// ap_item_type_colors). Governs ONE thing: the colour of the Archipelago-logo
	// markers in the pad glow. 1 (or any nonzero) = the AP classification tints --
	// plum progression, slate blue useful, cyan filler, salmon trap -- which is
	// what every shipped client renders. 0 = every marker wears one uniform
	// colour, so which KIND of AP item a pad holds stays a surprise.
	//
	// ADDITIVE key, no schema bump, and DELIBERATELY DEFAULTED TO 1: the apworld
	// half of #212 lands after the 0.2.0 name freeze, so this client has to run
	// against seeds that carry no such key at all. Absent -> 1 -> today's
	// behaviour, never the new one. Display only: it steers no gate, no location,
	// no item and no logic (the #65 lesson does not bite here).
	//
	// EXPECTED WIRE KEY: "ap_item_type_colors" (int or bool). If the apworld half
	// ships a different name, THIS is the line that changes -- and the option's own
	// docstring must then describe what the game actually does (Lessons §12).
	int ap_item_type_colors;

	// DeathLink (issue #6). ADDITIVE ctr_options keys, no schema bump: a seed
	// predating them leaves death_link 0 (off) and deathlink_amnesty 1, so the
	// feature stays dark on old seeds (the one_lap_cups additive-key precedent).
	//   death_link:        0 off / 1 mask_reset / 2 any_hit
	//   deathlink_amnesty: send one death per N eligible deaths (>= 1; 1 = every)
	int death_link;
	int deathlink_amnesty;

	// Progressive Boost (issue #12) + Progressive Stats (issue #13). ADDITIVE
	// ctr_options keys, no schema bump -- schema 7 is already unconditional on
	// every 0.2.0 seed (Q28), so these ride it exactly the way one_lap_cups and
	// death_link rode theirs. A seed predating them leaves all three at 0, which
	// IS the vanilla kart, so an old seed on a new client changes nothing.
	//   boost_mode / stats_mode: 0 off / 1 shared_global / 2 per_character, read
	// independently per pack. Both live modes are consumed; in mode 2 the applied
	// chain is the one belonging to the character being driven (item indices
	// 31..94, roster order). The apworld still raises OptionError for mode 2 today
	// (dowlle/ctr-native-ap#71, location supply), so no generated seed carries it
	// yet -- the wire path is real, the supply is not. Anything outside 0/1/2 is
	// treated as off by ap_capability.c rather than guessed at.
	//   boost_blue_fire: adds the blue-fire capstone above USF (3 received copies
	// instead of 2). No effect while boost_mode is 0. See ap/ap_capability.h.
	int boost_mode;
	int boost_blue_fire;
	int stats_mode;

	// ── Character phase (issues #54 / #209) ────────────────────────────────
	// All additive keys under the already-unconditional schema 7. Absent ->
	// the defaults set in ctr_cfg_reset, which reproduce pre-character-phase
	// behaviour exactly (starting racer = Crash, no unlock economy, no locks,
	// vanilla stats).
	//
	//   starting_character: the ENGINE `enum Characters` value 0..15, NOT an
	// apworld roster slot. The apworld does the mapping (worlds/ctr/
	// characters.py ROSTER_CHARACTER_ID, the mirror of this repo's own
	// ap_capability.c AP_CAP_ROSTER_CHARACTER), so nothing here has to.
	int starting_character;
	//   starting_stat_class: 0 vanilla (keep the racer's own class) / 1
	// balanced / 2 acceleration / 3 speed / 4 turning. Applies to the STARTING
	// racer only and never to a racer you unlock.
	int starting_stat_class;
	//   character_unlocks: 1 = the other 15 racers arrive as items, 0 = the
	// ruled all-unlocked comfort mode (every racer available immediately, no
	// unlock items exist in the seed at all).
	int character_unlocks;
	//   racer_locked_pads: 1 = this seed carries racer locks. The locks
	// themselves are in `racer_lock` below; this scalar exists so the client
	// can tell "locks off" from "seed predates the feature" without inferring
	// it from an empty array.
	int racer_locked_pads;
	//   penta_stats: 0 pal (Penta keeps his own TURN-class table) / 1 ntsc
	// (the PAL/JP fifth "MAX" class, a best-of-each-axis cherry-pick of the
	// four normal classes -- the same table USAUnlimitedPenta ships). ONLY
	// meaningful while stat_source is vanilla; see below.
	int penta_stats;
	//   editable_stats: the RAW option, kept for diagnostics only. The stat
	// panel must read the three resolved fields below, never this one.
	int editable_stats;
	//   The RESOLVED stat configuration. The apworld owns the ruled
	// progressive-vs-editable precedence in exactly one function
	// (characters.effective_stat_config) and sends the OUTCOME, so this client
	// must not re-implement the rule -- that split between "the text, the
	// rules and the engine" is what Lessons Learned #12 is about.
	//   stat_source: 0 vanilla class stats / 1 progressive received chains /
	// 2 the player's own editable package.
	int stat_source;
	//   stat_owner: 0 none / 1 global / 2 per_character. The granularity the
	// panel labels and the package is keyed by.
	int stat_owner;
	//   stat_editing_allowed: 1 = the panel exposes an edit control. Never 1
	// while stat_source is progressive; the apworld guarantees that.
	int stat_editing_allowed;
	//   character_phase_present: did this seed's ctr_options actually CARRY the
	// character-phase keys? This is key PRESENCE, deliberately not inferred from
	// the values above, because the two cases it separates are otherwise
	// identical: an old seed with none of these keys, and a NEW 0.2.0 seed that
	// explicitly set character_unlocks false with Crash as the starter and
	// vanilla stats. In the second case all 16 racers ARE available and the hub
	// picker is the only way to choose among them, so hiding it would delete the
	// feature exactly where the player needs it most. The character-phase
	// apworld emits every one of these keys on EVERY seed, on or off, which is
	// what makes presence a reliable signal.
	int character_phase_present;

	// The generating apworld's own world_version (issue #150), verbatim from
	// ctr_options.world_version -- e.g. "0.1.5", no "v" prefix. Under the release
	// policy that string IS the pair version, so a value higher than this build's
	// CTR_AP_VERSION proves a newer client exists; that is the entire basis of the
	// zero-network update notice (AP_DrawTitleUpdateNotice, ap_hooks.c).
	// ADDITIVE key, no schema bump: absent -> EMPTY string, which every consumer
	// reads as "unknown" and answers with silence. Never parsed for meaning here
	// (that is ap_version_cmp.h's job) and never read by a gate, check or item.
	char world_version[CTR_CFG_VERSION_CAP];

	int             warp_pad_map[CTR_CFG_PAD_COUNT];    // physical pad LevelID -> target trackID (identity default)
	ctr_warp_unlock warp_pad_unlock[CTR_CFG_PAD_COUNT]; // per-pad two-stage resolved reqs (stage1.type 0 = native vanilla rule)
	// Gem cups (CupRed..CupPurple = LevelID 100..104) live OUTSIDE the 28-wide
	// warp_pad_unlock array, so their per-seed randomized unlock requirement is
	// stored here, keyed by cup colour 0..4 = R,G,B,Y,P (= LevelID - 100). The
	// apworld emits these under the same warp_pad_unlock object using string keys
	// "100".."104"; the parser routes those keys into this array. stage1.type 0 =
	// fall back to the Phase-1 "4 tokens of this colour" rule. stage2 unused (gem
	// cups have no tier-2 menu); kept as ctr_warp_unlock only for parse symmetry.
	ctr_warp_unlock gem_cup_unlock[5];                  // gem cups by colour (LevelID 100..104); stage1.type 0 = native vanilla rule
	// Racer-locked pads (#54/#209). Parallel to warp_pad_unlock and keyed the
	// same way (physical pad LevelID), holding the ENGINE character id a pad
	// demands, or -1 for "no racer lock on this pad". A lock is ANDed ON TOP OF
	// warp_pad_unlock[pad], never in place of it: the apworld emits it as its
	// own top-level `racer_locks` block precisely so it cannot overwrite the
	// stage-1 requirement the sphere search proved reachable there. Cup pads
	// (LevelID 100..104) get the same treatment in gem_cup_racer_lock.
	int racer_lock[CTR_CFG_PAD_COUNT];
	int gem_cup_racer_lock[5];
	// slot_data v3 (destination-shuffle categories): the destination LevelID that
	// physical cup pad 100+i LOADS, keyed by cup colour 0..4 (= LevelID - 100).
	// Identity default (gem_cup_map[i] == 100 + i) until warp_pad_map overlays it,
	// exactly like warp_pad_map's identity base for 0..27. Under `merged` grouping a
	// value here may be ANY {0..27, 100..104} (a cup pad hosting a race/arena/other
	// cup); ctr_cfg_warp_dest/ctr_cfg_warp_phys read this array alongside
	// warp_pad_map so the phys<->dest mapping is a single permutation over the union.
	int             gem_cup_map[5];                     // phys cup LevelID 100+i -> destination LevelID (identity default 100+i)
	// Gem Cup leg tracks (issue #166, slot_data schema >= 7). Keyed by cup colour
	// 0..4 (= LevelID - 100) x leg 0..3 (cup-major, matching data.advCupTrackIDs's
	// own flat cup*4+leg layout). This isolated C++ lib has no access to `data`,
	// so the identity/vanilla default is NOT a formula here (unlike gem_cup_map's
	// 100+i): it is pushed in once at boot from the C side via
	// ctr_cfg_set_vanilla_cup_legs(), cached, and every parse re-seeds this array
	// from that cache before the (conditional) wire block overlays entries.
	// ctr_cfg_cup_leg() is the identity-safe accessor -- never read this array
	// directly.
	int             gem_cup_legs[5][4];                 // cup colour 0..4 (LevelID 100+i) -> leg 0..3 track LevelID (vanilla default)
	ctr_req         boss_req[CTR_CFG_BOSS_COUNT];       // 0 roo,1 papu,2 komodo,3 pinstripe,4 oxide
	// Per-boss required race-track LevelIDs for the track-based garage modes
	// (bossgarage_mode 0 Original4Tracks / 1 SameHubTracks). boss_tracks[b][0..
	// boss_n_tracks[b]-1] are the LevelIDs the player must have WON for boss b to
	// open; n==0 / entry -1 = no track list (mode 2 Trophies, or Oxide) -> use
	// boss_req. Emitted by the apworld under boss_garage_req[<boss>].tracks.
	int             boss_tracks[CTR_CFG_BOSS_COUNT][4];
	int             boss_n_tracks[CTR_CFG_BOSS_COUNT];

	// Podium placement checks (feat/podium-checks). enabled/any_position mirror
	// the two apworld toggles; podium[levelID] holds the per-track rung codes for
	// the 16 trophy races. The native fan-out (ap_hooks.c AP_RaceListenerTick)
	// reads these at the finish-line capture point. Additive block -- absent from
	// pre-podium seeds, in which case podium_enabled stays 0 and no rung fires.
	int              podium_enabled;      // podium_checks.enabled
	int              podium_any_position; // podium_checks.any_position
	ctr_podium_rungs podium[CTR_CFG_PODIUM_TRACK_COUNT]; // by trophy-race LevelID 0..15
} ctr_seed_config;

// Global config, zero-init; schema_version == 0 until ap_seedcfg_parse_json runs.
extern ctr_seed_config ctr_cfg;

// schema_version >= 1 (slot_data parsed and active).
int ctr_cfg_active(void);

// Remapped destination trackID for a physical pad LevelID. Accepts the full
// shuffle ID space: physical pads 0..27 (warp_pad_map) and cup pads 100..104
// (gem_cup_map). Identity (returns the input unchanged) when inactive or out of
// range -- safe to call unconditionally.
int ctr_cfg_warp_dest(int physPadLevelID);

// Inverse of ctr_cfg_warp_dest: given the destination trackID a pad currently
// LOADS (warppadObj->levelID after the LInB remap), return the PHYSICAL pad
// LevelID. Scans BOTH warp_pad_map (0..27) and gem_cup_map (100..104), so the
// destination (and the recovered physical pad) may be anywhere in {0..27,
// 100..104}. Identity (returns the input unchanged) when inactive, out of range,
// or when no pad maps to that destination. Used by AH_WarpPad_ThTick's load gate
// so the per-pad unlock requirement (keyed by PHYSICAL pad) is checked against
// the physical pad and not the remapped destination. The union of the two maps is
// a permutation over the participating pool, so the inverse is unique.
int ctr_cfg_warp_phys(int destTrackLevelID);

// One-time vanilla-table seed (issue #166). The C unity build (ap_hooks.c, which
// has `data` in scope) calls this ONCE at boot with data.advCupTrackIDs (20 ints,
// cup-major cup*4+leg, i.e. the table's own flat layout) so this isolated C++ lib
// never hand-copies it. Must run before the first ap_seedcfg_parse_json() for
// that seed's identity default (and ctr_cfg_cup_leg's inactive-state fallback)
// to be correct; safe to call again (idempotent last-write-wins).
void ctr_cfg_set_vanilla_cup_legs(const int *legs);

// The Gem Cup leg track LevelID for cup 0..4 (= LevelID - 100) x leg 0..3 (issue
// #166, schema >= 7). Identity-safe: returns the cached vanilla
// data.advCupTrackIDs value (via ctr_cfg_set_vanilla_cup_legs) when slot_data is
// inactive or this seed's wire block left the leg at its default; out-of-range
// cup/leg returns -1 (caller error, no sane fallback). Safe to call
// unconditionally, mirroring ctr_cfg_warp_phys.
int ctr_cfg_cup_leg(int cup, int leg);

// Is a warp pad's stage-1 LOAD gate satisfied? levelID is the PHYSICAL pad. When
// active and the pad has a per-seed requirement (type != 0), compares owned >=
// count for that requirement (colour-aware for tokens/gems). Otherwise falls back
// to that pad class's Phase-1 rule. Accepts BOTH the dense-array pads (0..27,
// vanilla fallback = received trophies >= numTrophiesToOpen) and cup pads
// (100..104 -> gem_cup_unlock[phys-100], vanilla fallback = 4 tokens of the cup's
// colour) -- required because under destination shuffle a race destination can be
// hosted on a cup PHYSICAL pad, and ThTick's load gate then calls this with a
// physical cup LevelID. Used by the load-time gate in AH_WarpPad_ThTick so the
// spawn visual and the load gate read one source.
//
// IMPLEMENTED C-SIDE in ap_hooks.c (not ap_seedcfg.cpp): it needs AP_GateCount*
// (received-item counters live in the C unity build) and the per-track
// numTrophiesToOpen threshold from data.metaDataLEV[] for the Phase-1 fallback,
// neither of which is reachable from the isolated C++ static lib.
int ctr_cfg_warp_unlocked(int levelID);

// The ENGINE character id a physical pad demands, or -1 when it carries no
// racer lock (#54/#209). Dense pads 0..27 and cup pads 100..104, keyed exactly
// like ctr_cfg_warp_unlocked. IMPLEMENTED C-SIDE in ap_hooks.c.
int ctr_cfg_racer_lock(int physPadLevelID);

// Is that pad's racer lock satisfied? Returns 1 for a pad with no lock, so a
// caller can AND it unconditionally. ctr_cfg_warp_unlocked already does; the
// separate accessor exists so the pad's own display can advertise the lock
// without re-deriving the rule. IMPLEMENTED C-SIDE in ap_hooks.c.
int ctr_cfg_racer_lock_met(int physPadLevelID);

// Is a trophy-track warp pad's STAGE-2 satisfied (open the relic Time Trials +
// CTR Token Challenge menu)? When active and the pad has a stage2 requirement
// (type != 0), compares owned >= count for stage2 (colour-aware for tokens/gems
// via AP_BossReqMet). type 0 (no stage2 / collapsed / flat-v1 slot_data) returns
// 1 (always open) so the tier-2 menu opens as soon as stage1 is met -- exactly
// the pre-two-stage behaviour. physPadLevelID is the PHYSICAL pad LevelID, the
// same key ctr_cfg_warp_unlocked uses. Accepts cup pads 100..104
// (-> gem_cup_unlock[phys-100].stage2): under `merged` shuffle a cup PHYSICAL pad
// can host a trophy-race destination, which per the contract §2 stage-2 rule
// carries a real stage2, so the cup pad's stage2 must be honoured here.
// IMPLEMENTED C-SIDE in ap_hooks.c.
int ctr_cfg_warp_stage2_unlocked(int physPadLevelID);

// The stage-2 requirement record for a physical pad, or NULL when it has none
// (type 0 / invalid id / slot_data inactive). Single source for the stage-2
// key logic: dense pads 0..27 via warp_pad_unlock, cup pads 100..104 via
// gem_cup_unlock. ctr_cfg_warp_stage2_unlocked and the LInB re-lock advert
// both resolve through it. IMPLEMENTED C-SIDE in ap_hooks.c.
const ctr_req *ctr_cfg_warp_stage2_req(int physPadLevelID);

// Typed comparator for a resolved requirement (boss garages + warp-pad load
// gate). Returns owned >= count for r->type using AP_GateCount* (colour-aware).
// type 0 / unknown -> 1 (no requirement). IMPLEMENTED C-SIDE in ap_hooks.c.
int AP_BossReqMet(const ctr_req *r);

// Per-mode boss-garage gate for the four boss hubs (bossIdx 0..3 = Roo, Papu,
// Komodo, Pinstripe). Honours bossgarage_mode: modes 0/1 (Original4Tracks /
// SameHubTracks) open the garage once every required race track for that boss
// has been WON (boss_tracks[bossIdx]); mode 2 (Trophies) and any boss with no
// track list fall back to the flat trophy-count requirement via AP_BossReqMet.
// IMPLEMENTED C-SIDE in ap_hooks.c (needs AP_LocationCheckedByBit).
int AP_BossGarageOpen(int bossIdx);

// #24: plain-text requirement advert for a boss-class gate (bossIdx 0..3 = the
// four boss garages, 4 = Oxide's garage door). Writes a line such as
// "Requires: 18 Gold Relics (have 12)" into `out` and returns 1; returns 0 when
// there is nothing to advertise (no slot_data -> the vanilla Aku hints are still
// accurate, so the caller must leave them as the only message). Mirrors the gate
// it describes: modes 0/1 advertise races won, everything else the resolved
// requirement. IMPLEMENTED C-SIDE in ap_hooks.c.
int AP_BossGateAdvert(int bossIdx, char *out, int cap);

// #152: plain-text requirement advert for the composed goal. Writes a line
// mirroring the exact AND of active conditions AP_EvaluateGoal checks (e.g.
// "Goal: beat N. Oxide (Final) AND win 2 of 4 boss races (1) AND hold 3
// Gems (1)") into `out` and returns 1; returns 0 when there is nothing to
// advertise (no slot_data). Same pattern as AP_BossGateAdvert -- reads the
// same ctr_cfg fields and AP_GateCount* helpers AP_EvaluateGoal reads, so the
// two cannot disagree. IMPLEMENTED C-SIDE in ap_hooks.c.
int AP_GoalAdvert(char *out, int cap);

#ifdef __cplusplus
} // extern "C"

#include <nlohmann/json.hpp>
// C++-only: parse the slot_data JSON into ctr_cfg. Called from ap_net.cpp.
void ap_seedcfg_parse_json(const nlohmann::json &j);
#endif

#endif // CTR_AP
#endif // AP_SEEDCFG_H
