// Native parser acceptance for ctr_options.color_boxes_by_item (AP item box
// colours, ruling R11). Compiles the REAL parser -- ap/ap_seedcfg.cpp is linked
// in, so there is no reimplementation to drift -- and parses two slot_data files
// generated by the apworld (tools/fixtures/box-colours/, same seed, option on
// and off, item box locations on). Those two files differ only in this key.
//
//   c++ -m32 -std=c++17 -DCTR_AP -Iap -Iap/vendor/json/include
//     tools/test-box-colour-seedcfg.cpp ap/ap_seedcfg.cpp
//     -o /tmp/test-box-colour-seedcfg && /tmp/test-box-colour-seedcfg
//
// Run from the repository root (the fixture paths are relative to it).
// Exit 0 = every assertion held.

#include <cstdio>
#include <fstream>
#include <nlohmann/json.hpp>

#include "../ap/ap_seedcfg.h"

extern void ap_seedcfg_parse_json(const nlohmann::json &j);

// The parser logs through the client's shim. This harness has no client.
extern "C" void AP_LogLine(const char *) {}

static int checks;
static int failures;

static void expect_int(int got, int want, const char *name)
{
	checks++;
	if (got != want)
	{
		failures++;
		std::printf("FAIL %s (got %d, want %d)\n", name, got, want);
	}
}

static nlohmann::json with(const nlohmann::json &value)
{
	nlohmann::json j = {{"ctr_options", {{"schema_version", 16}}}};
	if (!value.is_discarded())
		j["ctr_options"]["color_boxes_by_item"] = value;
	return j;
}

static void test_wire_values(void)
{
	ap_seedcfg_parse_json(with(nlohmann::json::value_t::discarded));
	expect_int(ctr_cfg.color_boxes_by_item, 0, "absent key -> pink boxes");
	ap_seedcfg_parse_json(with(true));
	expect_int(ctr_cfg.color_boxes_by_item, 1, "true -> item colours");
	ap_seedcfg_parse_json(with(false));
	expect_int(ctr_cfg.color_boxes_by_item, 0, "false -> pink");
	ap_seedcfg_parse_json(with(1));
	expect_int(ctr_cfg.color_boxes_by_item, 1, "1 -> item colours");
	ap_seedcfg_parse_json(with(2));
	expect_int(ctr_cfg.color_boxes_by_item, 1, "any nonzero -> item colours");
	ap_seedcfg_parse_json(with(0));
	expect_int(ctr_cfg.color_boxes_by_item, 0, "0 -> pink");
	ap_seedcfg_parse_json(with("yes"));
	expect_int(ctr_cfg.color_boxes_by_item, 0, "unparseable -> pink");
	ap_seedcfg_parse_json(with(nullptr));
	expect_int(ctr_cfg.color_boxes_by_item, 0, "null -> pink");
}

static void test_reparse_clears(void)
{
	ap_seedcfg_parse_json(with(true));
	ap_seedcfg_parse_json(nlohmann::json::object());
	expect_int(ctr_cfg.color_boxes_by_item, 0, "a seed without ctr_options does not inherit the last seed's colours");
	ap_seedcfg_parse_json(with(true));
	ap_seedcfg_parse_json(with(nlohmann::json::value_t::discarded));
	expect_int(ctr_cfg.color_boxes_by_item, 0, "an older seed does not inherit the last seed's colours");
}

static bool load(const char *path, nlohmann::json &out)
{
	std::ifstream in(path);
	if (!in)
		return false;
	out = nlohmann::json::parse(in);
	return true;
}

static void test_fixture(const char *name, int want)
{
	char path[256];
	nlohmann::json real;

	std::snprintf(path, sizeof path, "tools/fixtures/box-colours/%s.slot_data.json", name);
	checks++;
	if (!load(path, real))
	{
		failures++;
		std::printf("FAIL fixture missing: %s\n", path);
		return;
	}
	ap_seedcfg_parse_json(real);
	expect_int(ctr_cfg_active() ? 1 : 0, 1, "fixture seed is active");
	expect_int(ctr_cfg.schema_newer, 0, "fixture schema is known");
	expect_int(ctr_cfg.color_boxes_by_item, want, name);
}

int main(void)
{
	test_wire_values();
	test_reparse_clears();
	test_fixture("on_boxes_seed2026092319", 1);
	test_fixture("off_boxes_seed2026092319", 0);

	std::printf("%s box colour seedcfg (%d checks, %d failures)\n", failures ? "FAIL" : "PASS", checks, failures);
	return failures ? 1 : 0;
}
