# Custom-track package dependencies, authoring build only (CTR_AP_AUTHORING +
# CTR_CUSTOM_TRACKS). Packages need JSON and Unicode, not AP networking.
# Reuse the existing JSON pin; never invent a second version authority.
file(STRINGS "${CMAKE_SOURCE_DIR}/ap/vendor/versions.lock" _package_lock)
set(_package_section "")
set(_package_json_hash "")
foreach(_line IN LISTS _package_lock)
    if(_line MATCHES "^\\[(.+)\\]$")
        set(_package_section "${CMAKE_MATCH_1}")
    elseif(_package_section STREQUAL "json" AND _line MATCHES "^tree_sha256 = ([0-9a-f]+)$")
        set(_package_json_hash "${CMAKE_MATCH_1}")
    endif()
endforeach()
if(NOT _package_json_hash)
    message(FATAL_ERROR "Custom package JSON dependency has no pinned tree hash")
endif()
set(_package_json "${CMAKE_SOURCE_DIR}/ap/vendor/json")
if(NOT EXISTS "${_package_json}/include/nlohmann/json.hpp")
    message(FATAL_ERROR "Custom packages need the pinned JSON source under ap/vendor/json; see ap/vendor/fetch-deps.sh")
endif()
file(GLOB_RECURSE _package_files RELATIVE "${_package_json}" "${_package_json}/*")
list(SORT _package_files)
set(_package_manifest "")
foreach(_file IN LISTS _package_files)
    if(_file MATCHES "^\\.git/")
        continue()
    endif()
    file(SHA256 "${_package_json}/${_file}" _hash)
    string(APPEND _package_manifest "${_file} ${_hash}\n")
endforeach()
string(SHA256 _package_actual "${_package_manifest}")
if(NOT _package_actual STREQUAL _package_json_hash)
    message(FATAL_ERROR "Custom package JSON dependency differs from versions.lock")
endif()

file(STRINGS "${CMAKE_SOURCE_DIR}/vendor/utf8proc/SHA256SUMS" _unicode_lock)
set(_unicode_required LICENSE.md utf8proc.c utf8proc.h utf8proc_data.c)
foreach(_line IN LISTS _unicode_lock)
    if(NOT _line MATCHES "^([0-9a-f]+)  ([A-Za-z0-9_.]+)$")
        message(FATAL_ERROR "Malformed custom-package Unicode dependency pin")
    endif()
    set(_expected "${CMAKE_MATCH_1}")
    set(_file "${CMAKE_MATCH_2}")
    string(LENGTH "${_expected}" _digest_length)
    list(FIND _unicode_required "${_file}" _required_index)
    if(NOT _digest_length EQUAL 64 OR _required_index EQUAL -1)
        message(FATAL_ERROR "Unexpected or duplicate custom-package Unicode dependency pin")
    endif()
    list(REMOVE_ITEM _unicode_required "${_file}")
    file(SHA256 "${CMAKE_SOURCE_DIR}/vendor/utf8proc/${_file}" _actual)
    if(NOT _actual STREQUAL _expected)
        message(FATAL_ERROR "Custom-package Unicode dependency differs from pin: ${_file}")
    endif()
endforeach()
if(_unicode_required)
    message(FATAL_ERROR "Incomplete custom-package Unicode dependency pins")
endif()
message(STATUS "Custom package dependencies: pinned JSON verified; utf8proc 2.8.0 / Unicode 15.0.0 verified")
